{% set name = "mat_discover" %}
{% set version = "1.3.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mat_discover-{{ version }}.tar.gz
  sha256: 83d5110beb18c40b22a260eb74cfb938aee8f09714f3825792980dfd936ff3e5

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - flit
    - python
  run:
    - chem_wasserstein >=1.0.2
    - cudatoolkit ==11.3.1
    - pytorch >=1.9.0
    - python-kaleido
    - crabnet >=1.0.5
    - cython
    - dill
    - hdbscan
    - joblib
    - matplotlib-base >=3.4.3
    - numba >=0.53.1
    - pandas
    - plotly
    - pqdm
    - psutil
    - pymatgen
    - python
    - scikit-learn
    - scipy
    - seaborn
    - tqdm
    - umap-learn

test:
  imports:
    - mat_discover
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/mat_discover/
  summary: Data-driven materials discovery based on composition.
  dev_url: https://github.com/sparks-baird/mat_discover
  license: GPL-3.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - sgbaird
